name: timedoctorpro # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Time Doctor Pro client repackaged from timedoctorpro.com deb
description: |
  App to track work time from timedoctor.com

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  tdp:
    command: scripts/run.sh
    plugs: [
        home,
        desktop, #need for fonts
        network, network-bind,
        x11, #needed as it tracks mouse movement and other, will fail with bad call without
        opengl,
    ]


parts:
  timedoctorpro:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://updates.timedoctor.com/download/_production/tdpro/linux-ubuntu-17.04/timedoctorpro_1.4.75-15ubuntu17.04_amd64.deb
    source-type: deb
#    prepare: |
    override-build: |
        rm usr/bin/timedoctorpro
        snapcraftctl build
    stage-packages: [
      libx11-xcb1, libxcb1, libssl1.0.0, libqtcore4, libqtgui4, libqt4-dbus, libqt4-network, libqt4-sql, libqt4-sql-sqlite, libqt4-svg, libqt4-xml, libqt4-xmlpatterns, gksu, gdebi, libjpeg8, libpng12-0, libcv2.4, libxcb-record0 # from deb file
    ]
  launcher:
    plugin: copy
    files:
      run.sh: scripts/run.sh

